apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: main-app
  name: main-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
      - image: aldahdouh/random_string_app
        imagePullPolicy: IfNotPresent 
        name: random-string-app-62jcj
