apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pingpong-app
  name: pingpong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      volumes: # Define volume
        - name: shared-pingpong
          persistentVolumeClaim:
            claimName: pingpong-claim
      containers:
      - name: pingpong
        image: aldahdouh/pingpong
        imagePullPolicy: Always
        volumeMounts: # Mount 
          - name: shared-pingpong
            mountPath: /ping
        
